chore: update storybook and stories (#2007)
* chore(deps): update storybook/x

* chore: migrate addons to .storybook/main.js

* chore: migrate storybook config to .storybook/main.js

* chore(deps): fix storybook postCSS

* chore(deps): migrate static-dir flag to main.js

@see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

* chore: ignore storybook-static/

* chore(deps): use storybook-CRA dep

This addresses the following warning when running `npm run storybook`:

  WARN Storybook support for Create React App is now a separate preset.
  WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
  WARN The built-in preset has been disabled in Storybook 6.0.

* chore(deps): use webpack5 with storybook

@see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5

* fix: storybook webpack errors

Resolves the following error:

  Error: NormalModuleFactory.beforeResolve (IgnorePlugin) is no longer a
  waterfall hook, but a bailing hook instead. Do not return the passed
  object, but modify it instead. Returning false will ignore the request
  and results in no module created.

* fix: npm run storybook succeeds

but displays error in built website

* fix: Support CSFv3 storybook components

@see https://storybook.js.org/docs/react/api/csf

* chore: update Cid.stories.js

* fix: default storybook argTypes

* chore: update JsonEditor.stories.js

* chore: update AddFilesInfo.stories.js

* fix: Cid.stories.js

* chore: update info-boxes/**/*.stories.js

* update: breadcrumbs.stories.js

* chore: run storiesOf migration script

* Ran `git ls-files | grep 'stories.js' | xargs -n1 -- npx --yes sb migrate storiesof-to-csf --glob`
* Normalized default stories exports
  * Added jsdoc comment for default exports
  * export default as object literal

* chore: add jsdoc for story exports

* chore: update eslint rules

* disable default export rule for stories
* enable react/prop-types validation warning

* feat: Migrate FilesList.stories

* chore: update .storybook/main.js

* fix: mark PinningModal file prop as required

* feat: Finish migrating PinningModal story

* fix: remove countly.init error for storybook

* feat: Migrate remaining storybook stories

* fix: npm install and build

* fix: eslint should pass CI

* chore: fix typecheck failures

* fix: run @storybook/cli migrate storiesof-to-csf

Migrated leftover storiesOf stories with:
`npx @storybook/cli migrate storiesof-to-csf -g '**/(Radio|PublishModal).stories.js'`

* fix: run eslint --fix

* fix: build-storybook warnings & errors

* fix: PublishModal.stories.js renders properly

* feat: add test-storybook to CI

* chore: add test-storybook.yml